# These are supported funding model platforms

github: https://github.com/sponsors/creativepuru
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: 
