# These are supported funding model platforms

github: creativepuru
patreon: https://www.buymeacoffee.com/creativepuru
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: 
