# These are supported funding model platforms

github: https://github.com/sponsors/creativepuru    # GitHub Sponsor
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: https://www.buymeacoffee.com/creativepuru   # Buy Me a Coffee
